services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"  
    environment:
        DEEPL_URL: https://api-free.deepl.com/v2
        DEEPL_ACCESS_TOKEN: YOUR_ACCES_TOKEN
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    links:
      - backend
    ports:
      - "3000:3000"  
    depends_on:
      - backend
  